# Generated by Django 4.1.4 on 2022-12-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_route_id_trip_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='direction_code',
            field=models.CharField(max_length=32),
        ),
    ]
