# Generated by Django 4.1.4 on 2022-12-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_trip_direction_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Time',
            new_name='StopTime',
        ),
        migrations.AlterModelTable(
            name='stoptime',
            table='stop_times',
        ),
    ]
