# Generated by Django 4.1.4 on 2022-12-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_stoptime_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='stop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
