# Generated by Django 4.1.4 on 2022-12-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_stop_stop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='lest_x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stop',
            name='lest_y',
            field=models.FloatField(),
        ),
    ]
