# Generated by Django 4.1.4 on 2022-12-20 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_stoptime_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='api.route'),
        ),
    ]
